[package]
name = "wt"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
config = { version = "0.15.22", default-features = false, features = ["yaml"] }
directories = "6.0.0"
env_logger = "0.11.10"
git2 = { version = "0.20.4", default-features = false }
log = "0.4.29"
regex = "1.12.3"
serde = { version = "1.0.228", features = ["derive"] }
symlink-rs = "1.0.0"
thiserror = "2.0.18"
tmux_interface = "0.4.0"
